on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  cancel-pending:
    uses: slicelife/github-workflows/.github/workflows/cancel-pending.yml@main
    secrets:
      CANCEL_TOKEN: ${{ secrets.CANCEL_TOKEN }}

  releases-matrix:
    needs: cancel-pending
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.38
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://go.dev/dl/go1.20.4.linux-amd64.tar.gz"
        binary_name: "fetch-secrets"
        pre_command: export CGO_ENABLED=0
        compress_assets: false
